#!/bin/bash

# Resource list
resources=()

# Kubevirt namespace
resources+=(ns/kubevirt)

# VM
resources+=(virtualmachines)

# VMI
resources+=(virtualmachineinstances virtualmachineinstancereplicasets virtualmachineinstancepresets virtualmachineinstancemigrations)

# Run the collection of resources using must-gather
for resource in ${resources[@]}; do
  /usr/bin/oc adm inspect --dest-dir must-gather --all-namespaces ${resource}
done


# Collect the CRDs
/usr/bin/gather_crds

# Collect the CRs explicitely - some of them, like VMs, are collected by steps below
/usr/bin/gather_crs

# Collect the apiservices
/usr/bin/gather_apiservices

# Collect namespaces that contains VMs
/usr/bin/gather_vms_namespaces

# Collect VMs details
/usr/bin/gather_vms_details

exit 0
